### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by slashn** [epistemex/canvas-to-tiff#2]
Not so much an issue, but need help to figure out compression.
The average sample output tiff file size is around 8MB. I was looking to keep the file under 1MB.

I tried changing different values for the following lines, but with no success.
`			addEntry(0x102, 3, 4, offset, 8);  // BitsPerSample`
`			addEntry(0x103, 3, 1, 5);		    // Compression` 
I keep getting invalid 'BitsPerSample'.

Please help.

**Comment by epistemex** [comment]
BitsPerSamples must always be 8. This refers to the byte values in the raw bitmap. At this time no compression scheme is supported so it won't help changing the compression flag. But I'll add ZIP compression to the todo list for this project. This gives generally better compression than the older LZW.

**Comment by epistemex** [comment]
ZIP compression support added via options `compression` (boolean, default false) and `compressionLevel` (number 0-6, default 6). Requires https://github.com/nodeca/pako and the deflate module (included with canvas-to-tiff).

**Comment by slashn** [comment]
Thanks! I verified. It works fine. Thank you.
