### ISSUE TITLE
multi page tiff

### ISSUE THREAD

**Issue by Anas-Omar** [epistemex/canvas-to-tiff#3]
Hey man hope you are doing well , you did  really great job in this tool , but i am wondering if this tool support multi page tiff ?? i am struggling in the point of create a multi page tiff,  i tried to play with the IDF but i couldn't make anything   :( , so please can you help me in anyway ??

thank you very much

**Comment by epistemex** [comment]
it would unfortunately require a rewrite to allow "streaming"/adding pages to the container.
